config/routes.rb
Rails.application.routes.draw do



  
get 'home/index'
root 'home#index'
resources :users
resources :sessions, only: [:new, :create, :destroy]
get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'welcome', to: 'sessions#welcome', as: 'welcome'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/welcome'
  resources :users
  get 'book/add'
  get 'book/delete'
 
  get 'book/search'
  get 'book/save'
  get 'book/list'
  get 'book/new'
  get 'book/show'
  get 'first/login'
  get 'book/create'
  get 'book/destroy'
  get 'book/edit'




get 'display/hello'
get 'first/welcome'

#root 'first#welcome'
get "/first", to: "first#welcome"

match ':controller(/:action(/:id(.:format)))',:via => [:get,:post]





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/information.rb
class Information < ApplicationRecord


	
end

app/models/user.rb
class User < ApplicationRecord
 has_secure_password
 validates :email, presence: true, uniqueness: true
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
	if session[:user_id]
  	@current_user ||= User.find(session[:user_id])
	else
	@current_user = nil
	end
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  def add
    @book=Book.new(book_params)
    if @book.save
      redirect_to(action:'list')
    else
      flash[:notice]="Error:Record is not created"
      render(action:'new')
     end 
     
  end

  def delete
    @book = Book.find(params[:id])
  end

  

  def search
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to :action => 'list'
    else
      render :action => 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
     if @book.update_attributes(book_params)
      redirect_to(action: 'list')
    else
      render("edit")
       
     end
  end
 

  def list
    @book = Book.all
  end
  def new 
    @book=Book.new
  end

  def destroy
    bk = Book.find(params[:id])
    bk.destroy
    redirect_to(action: 'list')
     
  end


  def book_params
    params.require(:books).permit(:bname, :author, :price)
  end
end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
end

app/controllers/first_controller.rb
class FirstController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
end

 def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
     session[:user_id] = user.id
     redirect_to(action: 'welcome')
   else
     flash.now[:alert] = "Email or password is invalid"
     render "new"
   end
 end

 def destroy
   session[:user_id] = nil
   redirect_to root_url, notice: "Logged out!"
 end

def welcome
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :mobile, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/display_helper.rb
module DisplayHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book/add.html.erb
<h1>Add book detail here</h1>
<body>
<div class="box">
	<h2>Add New Book</h2>

	<%= form_for(:books,url:{controller:"book",action:'add'}) do |t| %>

	Name: <%=t.text_field(:bname)%><br>
	Author:<%= t.text_field(:author)%><br>
	Price:<%=t.text_field(:price)%><br>

	<%= submit_tag("add book")%><br>
<% end %>	
  <%= link_to "Back to list", controller:"book" , action:'list',class: "back-link"%>


</div>	



</body>

app/views/book/delete.html.erb
<div class="Book Delete">

 <h2>delete book</h2>
<%= form_for(:books,url:{action:'destroy',id:@book.id}) do |t|%>
<p>are you sure want to delete this permanently</p>
<p class ="reference.name"> <%= @book.bname %></p>
<div class="form-button">
	<%= submit_tag("delete book")%>
</div>
 
<% end %>

</div>

app/views/book/edit.html.erb

<%= link_to "Back to List ", controller: "book", action: 'list',class: "back-link"  %>

<div class ="Book Edit">
	<h2> Edit Book</h2>

	<%= form_for(:books, url: {action: 'update', id: @book.id}) do |t| %>

	  <table summary="Topic form fields">
  
		<tr>
			<th> Book Name </th>
			<td> <%= t.text_field(:bname)  %></td>
		</tr>
		
		<tr>
			<th> Author </th>
			<td> <%= t.text_field(:author)  %></td>
		</tr>

		<tr>
			<th> Price </th>
			<td> <%= t.text_field(:price)  %></td>
		</tr>
		
		
	</table>
	<div class = "form-button">
		<%= submit_tag("Update Book") %>
	</div>
	<% end %>





app/views/book/list.html.erb
<head>
  
  <link href="style.css" rel="stylesheet"
</head>
<% @book_title="Book"%>
<%= link_to "Back to home",controller:"first",action:'welcome',class: "back_link"%>

<div class="Book Index">

    <h1>Book list</h1>
 
    <%= link_to "Add new book",controller:'book',action:'new', class: "action new"%>
    <br>
    <br>
    <table class="listing" summury="book list" style="width: 50%" >
      <tr class="header">
        <th>Name</th>
        <th>Action</th>
      </tr>
        <tr>
            
        </tr>

      <% @book.each do |b| %>
           <tr>
               <td> <%= b.bname %></td>
               <td class = "actions">

                   <%= link_to "show", action:'show', id:b.id, class:"action show"%>
                   <%= link_to "edit", action:'edit', id:b.id, class:"action edit"%>
                   <%= link_to "delete", action:'delete', id:b.id, class:"action delete"%>
               </td>


           </tr>
        
        <% end %>








    </table>
    </div>

app/views/book/new.html.erb

<%= link_to "Back to List ", controller: "book", action: 'list',class: "back-link"  %>

<div class ="Books">
	<h2> add new Book</h2>

	<%= form_for(:books, url: {action: 'create', id: @book.id}) do |t| %>

	  <table summary="Topic form fields">
  
		<tr>
			<th> Book Name </th>
			<td> <%= t.text_field(:bname)  %></td>
		</tr>
		
		<tr>
			<th> Author </th>
			<td> <%= t.text_field(:author)  %></td>
		</tr>

		<tr>
			<th> Price </th>
			<td> <%= t.text_field(:price)  %></td>
		</tr>
		
		
	</table>
	<div class = "form-button">
		<%= submit_tag("createBook") %>
	</div>
	<% end %>

app/views/book/save.html.erb
<h1>Book#save</h1>
<html>
<head>
<meta charset="UTF-8">
<title>Save</title>

</head>
<body>

Successful..!!!

</body>
</html>

app/views/book/search.html.erb
<h1>search book</h1>

<html>
<head>

	
	<link href="style.css" rel="stylesheet"
</head>
<meta charset="UTF-8">
<title>search</title>
</head>
<body>
	<center>
		
		<h1><u><b>Search</b></u></h1>
		
		
		<input type="t" name="" id="">
		<button>search</button>
		<table border="1" style="width: 100px; text-align: center;">
			<tbody>
						</tbody>
			<thead>
				<tr>

					<td>bookName</td>
					<td>price</td>
					<td>author</td>
					

				</tr></thead>
			
		</table>

		<center>
</body>

</html>





<h1></h1>
<p>
	
	
	
</p>
<hr />

app/views/book/show.html.erb

<head>
	
	<link href="style.css" rel="stylesheet">
</head>

<h1><%= @book.bname %></h1>
<p>
	<strong>Price : </strong>$<%= @book.price %><br />
	<strong>Author : </strong>$<%= @book.author %><br />
	<strong>Created date : </strong>$<%= @book.created_at  %><br />

</p>
<hr />
<%= link_to 'Back',{:action =>'list'}%>

app/views/home/index.html.erb
<% if current_user %>
 Logged in as <%= current_user.email %>.
 <%= link_to 'Log Out', logout_path %>
<% else %>
 <%= link_to 'Sign Up', signup_path %> or
 <%= link_to 'Log In', login_path %>
<% end %>
<p id='notice'><%= notice %></p>
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Student</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.mobile %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to "Back ", controller: "home", action: 'index', class: "back-link"  %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>